### PR TITLE
[WIP] Timer

### PR DESCRIPTION
**Pull request by leobalter**

### CODE REVIEW

**Comment by luanmuniz** [comment]
What is the purpose of this function? Maybe i can help

**Comment by leobalter** [comment]
basically fake and manipulate setTimeout and setInterval.

this helps a lot many projects that relies on async calls, timeouts and timers in general, fastening many tests.

Example: https://github.com/rwaldron/johnny-five/blob/master/test/led.js#L153-L168

Basically the objective here is to make a replacement for setTimeout and setInterval that can later be restored.

**Comment by leobalter** [comment]
@raphamorim, I'm not sure if @luanmuniz is also working on this one, but I would love to release this feature

**Comment by raphamorim** [comment]
Cool, i'll check it too :)

**Comment by luanmuniz** [comment]
I'm working on this too. I'll probably finish this feature still this week.
Want to try the xhr2? \o/

**Comment by leobalter** [comment]
Finish this, Raphael could try the xhr2 stuff.

2014-09-19 10:43 GMT-03:00 Luan Muniz notifications@github.com:

**Comment by raphamorim** [comment]
Okay, i'll check xhr2 issue :octocat:

**Comment by leobalter** [comment]
@luanmuniz: we should check if [`requestAnimimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window.requestAnimationFrame) should be included on the timer too.

**Comment by luanmuniz** [comment]
\o/
@leobalter can you take a look on this and see if there is any feature missing? o/
If everything is ok, i'll make that blank commit

About the requestAnimationFrame, it is a helper for animations and timeframe of animations.
I don't think that it should be here. it is a animation render helper, not a [windowTimer](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers) function.

**Comment by leobalter** [comment]
Still not working on qunitnode tests, maybe just some adjustments missing

**Comment by luanmuniz** [comment]
What was the last commits, what they change? 
My last build was working and the commits are together now, i cant see what was the last change.

**Comment by leobalter** [comment]
Your build had `tearDown` instead of `teardown` on the Timer test hooks. With that it didn't restored the setTimeout, causing an error on qunitnode task.

**Pull request merged**
